### ISSUE TITLE
Fix area unit selection update issue

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#52] opened 2023-06-14 21:41 UTC
currently the area unit selection is not updating the table, fix this...

**Comment by monaw** [comment] 2023-06-23 20:47
hi @sinkovit , updating the area units by calling the animalAttributes() function doesn't seem to be working right.  i have added some print statements for debugging and even though animalAttributes is given the correct areaUnit parameter, it seems the result is not changing...here's the output of my debugging print statements:
```
Calculating spatial attributes...[1] "animalAttributes: areaUnits = ha"
[1] "animalAttributes: area_mcp = 101.830444970703"
[1] "animalAttributes: areaString = Area (ha)"
 [1] "animalAttributes: result = 1"       "animalAttributes: result = 766841" 
 [3] "animalAttributes: result = 768342"  "animalAttributes: result = 3724208"
 [5] "animalAttributes: result = 3725388" "animalAttributes: result = 101"    
 [7] "animalAttributes: result = 50x39"   "animalAttributes: result = 25x19"  
 [9] "animalAttributes: result = 15x11"   "animalAttributes: result = 5x3"    
done
input$areaunits = m2 
Re-calculating spatial attributes...[1] "animalAttributes: areaUnits = m2"
[1] "animalAttributes: area_mcp = 1018304.44970703"
[1] "animalAttributes: areaString = Area (m2)"
 [1] "animalAttributes: result = 1"         "animalAttributes: result = 766841"   
 [3] "animalAttributes: result = 768342"    "animalAttributes: result = 3724208"  
 [5] "animalAttributes: result = 3725388"   "animalAttributes: result = 1.018e+06"
 [7] "animalAttributes: result = 50x39"     "animalAttributes: result = 25x19"    
 [9] "animalAttributes: result = 15x11"     "animalAttributes: result = 5x3"   
```   
it looks like area_mcp is changing but the result is not.  i have checked the code into our dev branch so feel free to pull from the latest commit, run and see the output...

**Comment by sinkovit** [comment] 2023-06-23 22:12
Thanks Mona, I'll try to take a look today. I've been wrapped up trying to get the mkde package ready to resubmit to CRAN

**Comment by sinkovit** [comment] 2023-06-25 03:52
Hi @monaw 

I downloaded the dev version and did some tinkering. I'm not sure if we're looking at the same problem. The area seems to be updating correctly in both the MCP and MKDE tabs. For example, when I switch between m2, ha and km2, the area associated with condor 269 switches between 8.470e+09, 847003 and 8470 as expected. 

Now what doesn't seem to work any longer is generating the MCPs. In place of the plot, I get "Error: [object Object]" in red text. Now this could be a problem with my local R installation. I upgraded R and RStudio and it blew away all my installed packages. I _think_ that I reinstalled everything correctly, but maybe not.

**Comment by sinkovit** [comment] 2023-06-25 04:14
Hi @monaw 

Had you updated the dev branch since you posted the comment? I noticed that the area units is functioning correctly in dev but not in main. 

Btw, I can't get the MCP plots to work in main either or in any of the old branches I had laying around. Pretty sure that I broke something with my R installation

**Comment by sinkovit** [comment] 2023-06-26 21:48
Hi @monaw Just to clarify, am I being assigned the task of getting my R installation working or further investigating the units selection? My understanding was that you solved the latter.

**Comment by monaw** [comment] 2023-06-27 01:16
hi Bob, i thought the calculation for the area column in the table wasn't working but i realized i was looking at the wrong thing.  i just checked again and it seems the area column is correct, can you double check by running the latest dev and if you can verify that it is working, then feel free to close this ticket; otherwise, can you debug the issue and resolve?

**Comment by sinkovit** [comment] 2023-06-28 19:31
Just tested and confirmed that the area units are working correctly. Closing this issue.

**Closed by sinkovit** 2023-06-28 19:31 UTC
Labels: bug
